# Projekt do predmetu IPP (VUT FIT)
# Autor: Peter Kapicak (xkapic02)


instructions = [{'opcode':'MOVE',       'arg1':'var', 'arg2':'symbol' },
                {'opcode':'CREATEFRAME'},
                {'opcode':'PUSHFRAME'},
                {'opcode':'POPFRAME'},
                {'opcode':'DEFVAR',     'arg1':'var'},
                {'opcode':'CALL',       'arg1':'label'},
                {'opcode':'RETURN'},
                {'opcode':'PUSHS',      'arg1':'symbol'}, 
                {'opcode':'POPS',       'arg1':'var'}, 
                {'opcode':'ADD',        'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'},
                {'opcode':'SUB',        'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'MUL',        'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'IDIV',       'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'LT',         'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'},
                {'opcode':'GT',         'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'EQ',         'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'AND',        'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'OR',         'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'NOT',        'arg1':'var', 'arg2':'symbol'},
                {'opcode':'INT2CHAR',   'arg1':'var', 'arg2':'symbol'}, 
                {'opcode':'STRI2INT',   'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'READ',       'arg1':'var', 'arg2':'type'},
                {'opcode':'WRITE',      'arg1':'symbol'}, 
                {'opcode':'CONCAT',     'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'STRLEN',     'arg1':'var', 'arg2':'symbol'},
                {'opcode':'GETCHAR',    'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'SETCHAR',    'arg1':'var', 'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'TYPE',       'arg1':'var', 'arg2':'symbol'},
                {'opcode':'LABEL',      'arg1':'label'}, 
                {'opcode':'JUMP',       'arg1':'label'}, 
                {'opcode':'JUMPIFEQ',   'arg1':'label',    'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'JUMPIFNEQ',  'arg1':'label',    'arg2':'symbol', 'arg3':'symbol'}, 
                {'opcode':'DPRINT',     'arg1':'symbol'}, 
                {'opcode':'BREAK'}]

